PROG6212POE/Controllers/HRController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PROG6212POE.Controllers
{
    public class HRController : Controller
    {
        //[Authorize(Roles = "HR")]
        public IActionResult HRIndex()
        {
            return View();
        }
        //[Authorize(Roles = "HR")]
        public IActionResult Invoices()
        {
            return View();
        }

        public async Task<IActionResult> GenerateInvoice()
        {
            TempData["message"] = "Invoice generated successfully";
            return RedirectToAction("Invoices");
        }

        //[Authorize(Roles = "HR")]
        public IActionResult ListLecturers()
        {
            return View();
        }
        //[Authorize(Roles = "HR")]
        public IActionResult UpdateLecturerInformation()
        {
            return View();
        }

        public async Task<IActionResult> UpdateInformation()
        {
            TempData["message"] = "User updated successfully";
            return RedirectToAction("ListLecturers");
        }
    }
}

PROG6212POE/Controllers/UserAccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PROG6212POE.Areas.Identity.Data;

namespace PROG6212POE.Controllers
{
    public class UserAccountController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;

        public UserAccountController(SignInManager<ApplicationUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public IActionResult UserAccountDetails()
        {
            return View();
        }

        public IActionResult UpdateLecturerInformation()
        {
            return View();
        }



    }
}

PROG6212POE/Views/HR/HRIndex.cshtml
<h2>Welcome @User.Identity?.Name to the HR dashboard</h2>
<p>Select your action</p>
<br/>
<a asp-controller="HR" asp-action="Invoices">All invoices</a>
<br/>
<a asp-controller="HR" asp-action="ListLecturers">All lecturers</a>

PROG6212POE/Views/HR/Invoices.cshtml
<partial name= "_Toastr"/>
<br />
<div class="container col-md-10 mx-auto">
<h1>Current invoices</h1>
<hr />
<br />
<table class="table">
    <thead>
        <tr>
            <th style="background-color:mediumaquamarine" class="text-dark">Claim ID</th>
            <th style="background-color:mediumaquamarine" class="text-dark">Lecturer ID</th>
            <th style="background-color:mediumaquamarine" class="text-dark">Approved by</th>
            <th style="background-color:mediumaquamarine" class="text-dark">Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>text goes here</td>
            <td>text goes here</td>
            <td>text goes here</td>
            <td>
                <a asp-action="GenerateInvoice" class="btn btn-success">Generate Invoice</a>
            </td>
        </tr>
    </tbody>
</table>
</div>

PROG6212POE/Views/HR/ListLecturers.cshtml
<partial name="_Toastr" />
<br />
<div class="container col-md-10 mx-auto">
<h1>All lecturer</h1>
<hr />
<br />
<table class="table">
    <thead>
        <tr>
            <th style="background-color:mediumaquamarine" class="text-dark">Lecturer ID</th>
            <th style="background-color:mediumaquamarine" class="text-dark">Username</th>
            <th style="background-color:mediumaquamarine" class="text-dark">Email</th>
            <th style="background-color:mediumaquamarine" class="text-dark">Phone number</th>
            <th style="background-color:mediumaquamarine" class="text-dark">Action</t>
        </tr>
    </thead>
    <tbody class="text-muted">
        <tr>
            <td>text goes here</td>
            <td>text goes here</td>
            <td>text goes here</td>
            <td>text goes here</td>
            <td>
                <a asp-action="UpdateLecturerInformation" asp-controller="UserAccount" class="btn btn-info">Update user</a>
            </td>
        </tr>
    </tbody>
</table>
</div>